FROM fedora:44
WORKDIR /home/app
EXPOSE 8080
RUN dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
    && dnf install -y \
    mkvtoolnix \
    ffmpeg \
    mesa-va-drivers-freeworld \
    libva \
    libva-intel-driver \
    intel-media-driver \
    && dnf clean all
COPY ./server/build/native/nativeCompile /home/app
ENTRYPOINT ["/home/app/server"]
