package app.ister.core.entity;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

import java.util.List;

@Entity
// Identity is the normalized name, not the exact one: the unique index lives on
// (library_entity_id, name_normalized) and is created by Flyway (V43), not by Hibernate.
@Getter
@SuperBuilder
@NoArgsConstructor(access = AccessLevel.PUBLIC)
public class PersonEntity extends BaseEntity {

    // Nullable: persons created from TMDB cast credits don't belong to a music library.
    @Setter
    @ManyToOne
    private LibraryEntity libraryEntity;

    @Setter
    @Column(nullable = false)
    private String name;

    @Setter
    @Column(unique = true)
    private Long tmdbId;

    @Setter
    private Integer birthYear;

    /**
     * Generated by PostgreSQL from {@link #name}; the identity key that makes "ABBA" and "Abba" one
     * artist. Read-only from Java — see {@link PersonNames#normalize}.
     */
    @Column(name = "name_normalized", insertable = false, updatable = false)
    @org.hibernate.annotations.Generated(event = {org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    private String nameNormalized;

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "personEntity")
    @OrderBy("name ASC")
    private List<AlbumEntity> albumEntities;

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "personEntity")
    private List<ImageEntity> imageEntities;

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "personEntity")
    private List<MetadataEntity> metadataEntities;

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "personEntity")
    private List<CreditEntity> creditEntities;
}
