# The libraries
#app.ister.disk.libraries[0].name=shows
#app.ister.disk.libraries[0].type=SHOW

# The directories
#app.ister.disk.directories[0].name=disk1
#app.ister.disk.directories[0].path=/disk1
#app.ister.disk.directories[0].library=shows
#app.ister.disk.directories[1].name=disk2
#app.ister.disk.directories[1].path=/disk2
#app.ister.disk.directories[1].library=shows
