package app.ister.core.enums;

public enum EventType {
    NEW_DIRECTORIES_SCAN_REQUEST,
    ANALYZE_LIBRARY_REQUEST,
    FILE_SCAN_REQUESTED,
    SHOW_FOUND,
    EPISODE_FOUND,
    MEDIA_FILE_FOUND,
    MOVIE_FOUND,
    NFO_FILE_FOUND,
    SUBTITLE_FILE_FOUND,
    IMAGE_FOUND,
}
