app.ister.typesense.enabled=${TYPESENSE_ENABLED:false}
app.ister.typesense.host=${TYPESENSE_HOST:localhost}
app.ister.typesense.port=${TYPESENSE_PORT:8108}
app.ister.typesense.protocol=${TYPESENSE_PROTOCOL:http}
app.ister.typesense.api-key=${TYPESENSE_API_KEY:}
app.ister.typesense.collection=${TYPESENSE_COLLECTION:media}
